Activity Analysis Report
===================================

This assignment makes use of data from a personal activity monitoring device. This device collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.

##Data

The data for this assignment can be downloaded from the course web site:

Dataset: Activity monitoring data [52K]
The variables included in this dataset are:

**steps**: Number of steps taking in a 5-minute interval (missing values are coded as NA)

**date**: The date on which the measurement was taken in YYYY-MM-DD format

**interval**: Identifier for the 5-minute interval in which measurement was taken

The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations in this dataset.


#Loading and preprocessing the data

The following code chunck unzip the activity.zip file then load the data using read.csv

The `echo = TRUE` parameter was added to the code chunk to enbale printing of the R code. 
This is useful for peer evaluators to be able to review the code.


```{r, echo=TRUE}
unzip("activity.zip", overwrite = TRUE)
data <- read.csv("activity.csv")
dim(data)
summary(data)
```




